Loaded 11 trajectories (out of 45) for a tot of 5557 samples!
Agent created an put in cuda
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    main()
  File "main.py", line 67, in main
    file_load = get_best_model(os.path.join(config.save_dir,config.task),config.task)
  File "/home/adriano/Desktop/behavioural_cloning/utils.py", line 145, in get_best_model
    if f'model_{task}.pth' in os.listdir(folder_path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/adriano/Desktop/behavioural_cloning/params/grasp'